name: Build and Test Django App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted  # ou 'ubuntu-latest' se não estiver usando runner próprio

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r rdgen/rdgen/requirements.txt

      - name: Run Django checks
        run: |
          source venv/bin/activate
          python rdgen/rdgen/manage.py check
