name: Build RDGen Django

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Mostrar caminho e conteúdo
        run: |
          echo "PWD:"
          pwd
          echo "Conteúdo atual:"
          ls -la

      - name: Mostrar versão do Python
        run: python3.10 --version

      - name: Atualizar pip
        run: python3.10 -m pip install --upgrade pip

      - name: Instalar dependências
        run: python3.10 -m pip install -r requirements.txt

      - name: Rodar testes Django
        run: python3.10 manage.py test
