name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-pc-windows-gnu

      - name: Add Windows target
        run: rustup target add x86_64-pc-windows-gnu

      - name: Build EXE (Windows target)
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: List output EXE
        run: ls -lh target/x86_64-pc-windows-gnu/release/
