name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: List current directory
        run: ls -lha

      - name: List rdgen folder
        run: ls -lha rdgen || echo "rdgen folder not found"

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-pc-windows-gnu

      - name: Add Windows target
        run: rustup target add x86_64-pc-windows-gnu

      - name: Build EXE (Windows target)
        run: cargo build --release --target x86_64-pc-windows-gnu
        working-directory: rdgen  # Ajusta se necessário

      - name: List output EXE
        run: ls -lh rdgen/target/x86_64-pc-windows-gnu/release/
